apiVersion: v1
kind: Template
parameters:
- name: APP_NAME
  required: true
- name: PUBLIC_NAME
  required: true
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    host: ${PUBLIC_NAME}.apps.openshift.novaordis.io
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
